### ISSUE TITLE
hdmi

### ISSUE THREAD

**Issue by evoart-studio** [rahulhingve/Hackintosh-MSI-GF63-Thin-9SCXR#1]
Hello, I'm using same laptop, with your efi all work, without hdmi... Any recommendations? Thx

**Comment by rahulhingve** [comment]
@evoart-studio 
I don't have a secondary monitor, so I haven't checked HDMI, but you can use my latest EFI https://github.com/rahulhingve/Hackintosh-Msi-GF63-Thin-9SCXR-Sonoma in which I fixed the late backlight display issues by mapping all the display ports while fixing the display problem, so maybe HDMI will work. Good luck!

**Comment by evoart-studio** [comment]
Yes, thx, I already download and making flash drive, thanks to you work

**Comment by rahulhingve** [comment]
Good luck! Make sure to generate a new serial number using the SMBIOS method mentioned in the guide after booting up.

**Comment by rahulhingve** [comment]
https://github.com/rahulhingve/Hackintosh-Msi-GF63-Thin-9SCXR-Sonoma have working hdmi
